test_0 (__main__.lab3a.test_0)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - Test for file creation: ./lab3a.py ... ok
test_1 (__main__.lab3a.test_1)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - Test for errors running: ./lab3a.py ... ok
test_2 (__main__.lab3a.test_2)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - Test for correct shebang line: ./lab3a.py ... ok
test_4_function_return_text_value (__main__.lab3a.test_4_function_return_text_value)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - function print_out_text() has correct output ... ok
test_5_function_return_number_value (__main__.lab3a.test_5_function_return_number_value)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - function print_out_text() has correct output ... ok
test_0 (__main__.lab3b.test_0)
[Lab 3] - [Investigation 2] - [Part 1] - Functions - Test for file creation: ./lab3b.py ... ok
test_1 (__main__.lab3b.test_1)
[Lab 3] - [Investigation 2] - [Part 1] - Functions - Test for errors running: ./lab3b.py ... ok
test_2 (__main__.lab3b.test_2)
[Lab 3] - [Investigation 2] - [Part 1] - Functions - Test for correct shebang line: ./lab3b.py ... ok
test_4_function_sum (__main__.lab3b.test_4_function_sum)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments - function sum_numbers() fails without 2 arguments ... ok
test_5_function_subtract (__main__.lab3b.test_5_function_subtract)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments - function subtract_numbers() fails without 2 arguments ... ok
test_6_function_multiply (__main__.lab3b.test_6_function_multiply)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments - function multiply_numbers() fails without 2 arguments ... ok
test_7_function_sum_output (__main__.lab3b.test_7_function_sum_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments - function add_numbers() adds correctly ... ok
test_8_function_subtract_output (__main__.lab3b.test_8_function_subtract_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments - function subtract_numbers() subtracts correctly ... ok
test_9_function_multiply_output (__main__.lab3b.test_9_function_multiply_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments - function multiply_numbers() multiplies correctly ... ok
test_0 (__main__.lab3c.test_0)
[Lab 3] - [Investigation 2] - [Part 1] - Functions - Test for file creation: ./lab3c.py ... ok
test_1 (__main__.lab3c.test_1)
[Lab 3] - [Investigation 2] - [Part 1] - Functions - Test for errors running: ./lab3c.py ... ok
test_2 (__main__.lab3c.test_2)
[Lab 3] - [Investigation 2] - [Part 1] - Functions - Test for correct shebang line: ./lab3X.py ... ok
test_4_function_sum (__main__.lab3c.test_4_function_sum)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() fails with 0 arguments ... ok
test_5_function_subtract (__main__.lab3c.test_5_function_subtract)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() fails with 1 arguments ... ok
test_6_function_multiply (__main__.lab3c.test_6_function_multiply)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() fails with 2 arguments ... ok
test_7_function_sum_output (__main__.lab3c.test_7_function_sum_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() adds correctly test 1 ... ok
test_8_function_subtract_output (__main__.lab3c.test_8_function_subtract_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() subtracts correctly test 1 ... ok
test_9_function_multiply_output (__main__.lab3c.test_9_function_multiply_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() multiplies correctly test 1 ... ok
test_a_function_sum_output (__main__.lab3c.test_a_function_sum_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() adds correctly test 2 ... ok
test_b_function_subtract_output (__main__.lab3c.test_b_function_subtract_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() subtracts correctly test 2 ... ok
test_c_function_multiply_output (__main__.lab3c.test_c_function_multiply_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() multiplies correctly test 2 ... ok
test_d_function_multiply_output (__main__.lab3c.test_d_function_multiply_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() fails with division ... FAIL

======================================================================
FAIL: test_d_function_multiply_output (__main__.lab3c.test_d_function_multiply_output)
[Lab 3] - [Investigation 2] - [Part 1] - functions & arguments & logic - function operate() fails with division
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rmendoza10/ops445/lab3/./CheckLab3.py", line 277, in test_d_function_multiply_output
    self.assertEqual(str(lab3cStudent.operate(5, 50, 'divide')), 'Error: function operator can be "add", "subtract", or "multiply"')
AssertionError: '0.1' != 'Error: function operator can be "add", "subtract", or "multiply"'
- 0.1
+ Error: function operator can be "add", "subtract", or "multiply"


----------------------------------------------------------------------
Ran 27 tests in 0.060s

FAILED (failures=1)
OPS445 Lab Report - System Information for running ./CheckLab3.py
=================================================================
    User login name: rmendoza10
    Linux system name: fedora
    Python executable: /usr/bin/python3
    Python version: 3125
    OS Platform: linux
    Working Directory: /home/rmendoza10/ops445/lab3
    Start at: Wed Sep 25 16:48:03 2024
=================================================================
